name: Java CI with Maven + SonarCloud [develop]

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.4'
        distribution: 'liberica'
        java-package: jdk+fx
        architecture: x64
    - name: Create dotenv File
      run: |
        touch /home/runner/work/PROJETO-III/PROJETO-III/.env
        echo DB_URL="${{ secrets.DB_URL }}" >> /home/runner/work/PROJETO-III/PROJETO-III/.env
        echo DB_USER="${{ secrets.DB_USER }}" >> /home/runner/work/PROJETO-III/PROJETO-III/.env
        echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> /home/runner/work/PROJETO-III/PROJETO-III/.env
        cat /home/runner/work/PROJETO-III/PROJETO-III/.env

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=italanleal_PROJETO-III        

    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: AcademicEvents
        path: target/*.jar
