name: Review Required Workflow

on:
  pull_request:
    branches: [ "review" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.4'
          distribution: 'liberica'
          java-package: jdk+fx
          architecture: x64
              
      - name: Build with Maven
        run: mvn -Dtest=NoneToTest -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: AcademicEvents
          path: target/*.jar
          
  review:
    runs-on: ubuntu-latest
    needs: build
    environment: reviewing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: UserTest

        run: |
          echo "This job requires a review before it can proceed"
