name: Review Required Workflow

on:
  push:
    branches: [ "review" ]

jobs:
  review-required-job:
    runs-on: ubuntu-latest
    environment: reviewing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some job
        run: |
          echo "This job requires a review before it can proceed"
